default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("CRYPTOCRUNCH_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: cryptocrunch_dev

test:
  <<: *default
  database: cryptocrunch_test

production:
  adapter: postgresql
  database: <%= ENV["CRYPTOCRUNCH_DB_NAME"] %>
  encoding: unicode
  host: <%= ENV["CRYPTOCRUNCH_DB_HOSTNAME"] %>
  password: <%= ENV["CRYPTOCRUNCH_DB_PASSWORD"] %>
  port: <%= ENV["CRYPTOCRUNCH_DB_PORT"] %>
  username: <%= ENV["CRYPTOCRUNCH_DB_USERNAME"] %>
